///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////
//! Autogenerated weights for `pallet_robonomics_digital_twin`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-10-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `DO-Premium-AMD`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_digital_twin
// --extrinsic
// 
// --template
// ./scripts/weights/frame-weight-template.hbs
// --output
// frame/digital-twin/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_robonomics_digital_twin`.
pub trait WeightInfo {
	fn create() -> Weight;
	fn set_topic() -> Weight;
	fn remove_topic() -> Weight;
}

/// Weights for `pallet_robonomics_digital_twin` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `DigitalTwin::TwinCount` (r:1 w:1)
	/// Proof: `DigitalTwin::TwinCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::Owner` (r:0 w:1)
	/// Proof: `DigitalTwin::Owner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `1588`
		// Minimum execution time: 16_559_000 picoseconds.
		Weight::from_parts(20_200_000, 1588)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `DigitalTwin::Owner` (r:1 w:0)
	/// Proof: `DigitalTwin::Owner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::Topics` (r:1 w:1)
	/// Proof: `DigitalTwin::Topics` (`max_values`: None, `max_size`: Some(600), added: 3075, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::TopicList` (r:1 w:1)
	/// Proof: `DigitalTwin::TopicList` (`max_values`: None, `max_size`: Some(3236), added: 5711, mode: `MaxEncodedLen`)
	fn set_topic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `6701`
		// Minimum execution time: 24_419_000 picoseconds.
		Weight::from_parts(31_829_000, 6701)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `DigitalTwin::Owner` (r:1 w:0)
	/// Proof: `DigitalTwin::Owner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::Topics` (r:1 w:1)
	/// Proof: `DigitalTwin::Topics` (`max_values`: None, `max_size`: Some(600), added: 3075, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::TopicList` (r:1 w:1)
	/// Proof: `DigitalTwin::TopicList` (`max_values`: None, `max_size`: Some(3236), added: 5711, mode: `MaxEncodedLen`)
	fn remove_topic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `6701`
		// Minimum execution time: 21_290_000 picoseconds.
		Weight::from_parts(24_150_000, 6701)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `DigitalTwin::TwinCount` (r:1 w:1)
	/// Proof: `DigitalTwin::TwinCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::Owner` (r:0 w:1)
	/// Proof: `DigitalTwin::Owner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `1588`
		// Minimum execution time: 16_559_000 picoseconds.
		Weight::from_parts(20_200_000, 1588)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `DigitalTwin::Owner` (r:1 w:0)
	/// Proof: `DigitalTwin::Owner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::Topics` (r:1 w:1)
	/// Proof: `DigitalTwin::Topics` (`max_values`: None, `max_size`: Some(600), added: 3075, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::TopicList` (r:1 w:1)
	/// Proof: `DigitalTwin::TopicList` (`max_values`: None, `max_size`: Some(3236), added: 5711, mode: `MaxEncodedLen`)
	fn set_topic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `6701`
		// Minimum execution time: 24_419_000 picoseconds.
		Weight::from_parts(31_829_000, 6701)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `DigitalTwin::Owner` (r:1 w:0)
	/// Proof: `DigitalTwin::Owner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::Topics` (r:1 w:1)
	/// Proof: `DigitalTwin::Topics` (`max_values`: None, `max_size`: Some(600), added: 3075, mode: `MaxEncodedLen`)
	/// Storage: `DigitalTwin::TopicList` (r:1 w:1)
	/// Proof: `DigitalTwin::TopicList` (`max_values`: None, `max_size`: Some(3236), added: 5711, mode: `MaxEncodedLen`)
	fn remove_topic() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `6701`
		// Minimum execution time: 21_290_000 picoseconds.
		Weight::from_parts(24_150_000, 6701)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
