[package]
name = "node-testing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
pallet-balances = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = { version = "0.9.0", features = ["test-helpers", "db"],  git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-db = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
codec = { package = "parity-scale-codec", version = "2.0.0" }
pallet-contracts = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-indices = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-keyring = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
node-primitives = { path = "../primitives" } 
node-runtime = { path = "../runtime" } 
node-cli = { path = "../cli" }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-io = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-support = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-session = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-society = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-staking = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-executor = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"] }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
substrate-test-client = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-timestamp = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-transaction-payment = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-treasury = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-timestamp = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-block-builder = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"

[dev-dependencies]
criterion = "0.3.0"
sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
