[target.x86_64-pc-windows-gnu]
image = "robonomics/cross:x86_64-pc-windows-gnu-0.2.1"

[target.i686-pc-windows-gnu]
image = "robonomics/cross:i686-pc-windows-gnu-0.2.1"

[target.i686-unknown-linux-gnu]
image = "robonomics/cross:i686-unknown-linux-gnu-0.2.1"

[target.aarch64-unknown-linux-gnu]
image = "robonomics/cross:aarch64-unknown-linux-gnu-0.2.1"

[target.armv7-unknown-linux-gnueabihf]
image = "robonomics/cross:armv7-unknown-linux-gnueabihf-0.2.1"
