[target.aarch64-unknown-linux-musl]
pre-build = [
  "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get --assume-yes install protobuf-compiler llvm-18 llvm-18-tools clang-18 && update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 200",
]
[target.riscv64gc-unknown-linux-gnu]
pre-build = [
  "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get --assume-yes install protobuf-compiler llvm-18 llvm-18-tools clang-18 && update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 200",
]
[target.x86_64-unknown-linux-musl]
pre-build = [
  "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get --assume-yes install protobuf-compiler llvm-18 llvm-18-tools clang-18 && update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 200",
]
