= Robonomics on Substrate
:Author: Robonomics developers
:Revision: 0.1.0
:toc:
:sectnums:

image:https://travis-ci.org/airalab/substrate-node-robonomics.svg?branch=master["Build Status", link="https://travis-ci.org/airalab/substrate-node-robonomics"]
image:https://img.shields.io/github/downloads/airalab/substrate-node-robonomics/total.svg["Downloads", link="https://github.com/airalab/substrate-node-robonomics/releases"]
image:https://img.shields.io/github/release/airalab/substrate-node-robonomics.svg["Release", link="https://github.com/airalab/substrate-node-robonomics/releases"]

== Intro

AIRA (Autonomous Intelligent Robot Agent) project implements the standard of economic interaction between human-robot and robot-robot via liability smart contract. AIRA makes it possible to connect a variety of different robots to the market of robot liabilities for the direct sale of data from robot sensors, ordering of logistics services, and organization ordering of personalized products at fully automated enterprises.

This source is a part of AIRA project. It implements their purposes using Substrate technologies.

== Try it out

 . Import https://github.com/airalab/substrate-node-robonomics/blob/master/res/custom_types.json[custom data types] at https://polkadot.js.org/apps/#/settings/developer[Substrate UI]: Developer settings
 . Open https://polkadot.js.org/apps/#/settings[Substrate UI]: General settings
 . Set `custom` node endpoint to `wss://substrate.robonomics.network`
 . Save and reload
 . Get test tokens at https://faucets.blockxlabs.com

When connection is success you can explore `Robonomics testnet` using Substrate UI.

 - Accounts management: https://polkadot.js.org/apps/#/accounts
 - Looking for network events: https://polkadot.js.org/apps/#/explorer
 - Transfer test XRT: https://polkadot.js.org/apps/#/transfer
 - Send extrinsics to robonomics module: https://polkadot.js.org/apps/#/extrinsics

== Install node

Robonomics on Substrate binary blobs available as an assets in https://github.com/airalab/substrate-node-robonomics/releases[releases]. Latest version you can try to build from source code.

=== Building from source

Ensure you have Rust and the support software installed:

[source, shell]
----
curl https://sh.rustup.rs -sSf | sh
# on Windows download and run rustup-init.exe
# from https://rustup.rs instead

rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
rustup update stable
cargo +nightly install --git https://github.com/alexcrichton/wasm-gc
----

You will also need to install the following packages:

 - Linux:
[source, shell]
sudo apt install cmake git clang libclang-dev

 - Mac:
[source, shell]
brew install cmake pkg-config git llvm

 - Windows (PowerShell):
+
[source, shell]
----
# Install LLVM
# Download and install the Pre Build Windows binaries
# of LLVM  from http://releases.llvm.org/download.html
----

Install robonomics node from git source:

[source, shell]
cargo +nightly install --force --git https://github.com/airalab/substrate-node-robonomics --tag v0.12

Run node in https://telemetry.polkadot.io/#/Robonomics[Robonomics testnet]:

[source, shell]
robonomics-node

Or run your local development network:

[source, shell]
robonomics-node --dev

=== Building with Nix

Install Nix package manager:

[source, shell]
curl https://nixos.org/nix/install | sh

Run in Nix shell:

[source, shell]
----
git clone https://github.com/airalab/substrate-node-robonomics && cd substrate-node-robonomics
nix-shell --run "cargo run --release"
----

== Network maintaining

Currently Robonomics on Substrate https://telemetry.polkadot.io/#/Robonomics[testnet] is maintained by developers but anyone can support the project by several ways described below.

=== Full node

You can support the network just by launch the node. Every additional full node of blockchain helps it to be more sustainable and fault tolerant. Robonomics node binaries is available on https://github.com/airalab/substrate-node-robonomics/releases[releases] or could be <<building-from-source,build from source>>.

=== Become a validator

For nodes that can be online 24/7 also available most important role on chain - block producers or briefly validator. Robonomics on Substrate use https://github.com/paritytech/substrate/blob/8930f297737db67257f3be1a8b286f8c50189066/srml/staking/Staking.md[NPoS algorithm] for choosing block production accounts. For this reason if you have any stake in testnet XRT then you can try self in block production. 

 . Launch node and wait for synchronization.
[source, shell]
robonomics-node

 . Open https://polkadot.js.org/apps/#/settings[Settings] and switch UI to `Local Node` mode (don't foget import https://github.com/airalab/substrate-node-robonomics/blob/master/res/custom_types.json[Custom Types] on https://polkadot.js.org/apps/#/settings/developer[Developer Settings]).

 . Generate session keys during RPC call at https://polkadot.js.org/apps/#/toolbox[Toolbox page]:
 .. Submit RPC call `author:rotateKeys()` and copy result, it will be required later.

 . Restart node in validator mode.
[source, shell]
robonomics-node --validator

 . Generate accounts at https://polkadot.js.org/apps/#/accounts/create[Account page]:
 .. create `stash` usign `Schnorrkel (sr25519)` crypto;
 .. create `controller` using `Schnorrkel (sr25519)` crypto.

 . Request testnet XRT in our https://matrix.to/#/#robonomics:matrix.org[Matrix room] or use https://faucets.blockxlabs.com[Faucet].
 . Transfer testnet XRT to `stash` and a little bit to `controller` account.

 . https://polkadot.js.org/apps/#/staking/actions[Staking actions]:
 .. call `New stake` for `stash` and `controller` accounts;
 .. call `Set Session Key` for result account pair and paste session key given in step before;
 .. call `Validate` action.

 . Check https://polkadot.js.org/apps/#/staking[Validator List], at new Era validator set will updated.

== Robotics integration

Special feature `ros` helps to use Robonomics Substrate modules in http://www.ros.org[ROS]-enabled cyber-physical systems.

=== Building with ROS feature

 . Install ROS using http://wiki.ros.org/melodic/Installation[instruction].

 . Import ROS environment:
[source, shell]
source /opt/ros/melodic/setup.bash

 . Build with `ros` feature:
[source, shell]
cargo build --release --features ros

=== Launch ROS node

 . Start ROS core service
[source, shell]
roscore

 . Start node:
[source, shell]
cargo run --release --features ros

 . Subscribe for best block number:
[source, shell]
rostopic echo /blockchain/best_number
