[toolchain]
channel = "1.93.0"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
  "wasm32v1-none",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
]
profile = "minimal"
