var N = null;var sourcesIndex = {};
sourcesIndex["alpha_runtime"] = {"name":"","files":["constants.rs","lib.rs","xcm_config.rs"]};
sourcesIndex["ipci_runtime"] = {"name":"","files":["constants.rs","lib.rs","voter_bags.rs"]};
sourcesIndex["local_runtime"] = {"name":"","files":["constants.rs","lib.rs"]};
sourcesIndex["main_runtime"] = {"name":"","files":["constants.rs","lib.rs","xcm_config.rs"]};
sourcesIndex["pallet_robonomics_datalog"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_robonomics_digital_twin"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_robonomics_launch"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_robonomics_liability"] = {"name":"","files":["economics.rs","lib.rs","signed.rs","technics.rs","traits.rs"]};
sourcesIndex["pallet_robonomics_lighthouse"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_robonomics_rws"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_robonomics_staking"] = {"name":"","files":["lib.rs"]};
sourcesIndex["robonomics"] = {"name":"","files":["main.rs"]};
sourcesIndex["robonomics_primitives"] = {"name":"","files":["lib.rs"]};
sourcesIndex["robonomics_rpc"] = {"name":"","files":["lib.rs"]};
sourcesIndex["robonomics_service"] = {"name":"","dirs":[{"name":"parachain","files":["chain_spec.rs","cli.rs","command.rs","service.rs"]}],"files":["chain_spec.rs","cli.rs","command.rs","lib.rs","parachain.rs","service.rs"]};
createSourceSidebar();
