[package]
name = "robonomics-runtime"
version = "0.11.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "4.1", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", default-features = false }
version = { package = "sr-version", git = "https://github.com/paritytech/substrate", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
offchain_primitives = { package = "substrate-offchain-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
executive = { package = "srml-executive", git = "https://github.com/paritytech/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/paritytech/substrate", default-features = false }
babe = { package = "srml-babe", git = "https://github.com/paritytech/substrate", default-features = false }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
consensus-primitives = { package = "substrate-consensus-common-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
authorship = { package = "srml-authorship", git = "https://github.com/paritytech/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/paritytech/substrate", default-features = false }
indices = { package = "srml-indices", git = "https://github.com/paritytech/substrate", default-features = false }
balances = { package = "srml-balances", git = "https://github.com/paritytech/substrate", default-features = false }
finality_tracker = { package = "srml-finality-tracker", git = "https://github.com/paritytech/substrate", default-features = false }
grandpa = { package = "srml-grandpa", git = "https://github.com/paritytech/substrate", default-features = false }
session = { package = "srml-session", git = "https://github.com/paritytech/substrate", default-features = false }
staking = { package = "srml-staking", git = "https://github.com/paritytech/substrate", default-features = false }
sudo = { package = "srml-sudo", git = "https://github.com/paritytech/substrate", default-features = false }
im-online = { package = "srml-im-online", git = "https://github.com/paritytech/substrate", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.2" }

[features]
default = ["std"]
std = [
    "serde",
    "serde_derive",
	"parity-codec/std",
	"rstd/std",
	"client/std",
	"version/std",
	"runtime_primitives/std",
    "offchain_primitives/std",
	"primitives/std",
	"executive/std",
	"support/std",
    "babe/std",
    "babe-primitives/std",
    "consensus-primitives/std",
    "authorship/std",
	"system/std",
	"timestamp/std",
    "indices/std",
	"balances/std",
    "finality_tracker/std",
    "grandpa/std",
    "session/std",
    "staking/std",
	"sudo/std",
    "im-online/std",
]
no_std = []
