///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `cumulus_pallet_xcmp_queue`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `krakov`, CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// cumulus_pallet_xcmp_queue
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/cumulus_pallet_xcmp_queue.rs
// --header
// /home/akru/devel/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 2
// --repeat
// 1
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `cumulus_pallet_xcmp_queue`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> cumulus_pallet_xcmp_queue::WeightInfo for WeightInfo<T> {
	fn set_config_with_u32() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `0`
		// Minimum execution time: 15_758_000 picoseconds.
		Weight::from_parts(15_758_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[0, 105467]`.
	fn enqueue_n_bytes_xcmp_message(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `0`
		// Minimum execution time: 29_315_000 picoseconds.
		Weight::from_parts(171_612_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[0, 1000]`.
	fn enqueue_n_empty_xcmp_messages(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `0`
		// Minimum execution time: 24_401_000 picoseconds.
		Weight::from_parts(230_569_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[0, 105457]`.
	fn enqueue_empty_xcmp_message_at(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294 + n * (1 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 37_556_000 picoseconds.
		Weight::from_parts(309_849_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[0, 100]`.
	fn enqueue_n_full_pages(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `0`
		// Minimum execution time: 26_584_000 picoseconds.
		Weight::from_parts(8_036_338_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn enqueue_1000_small_xcmp_messages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `53034`
		//  Estimated: `0`
		// Minimum execution time: 385_818_000 picoseconds.
		Weight::from_parts(385_818_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn suspend_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `0`
		// Minimum execution time: 6_151_000 picoseconds.
		Weight::from_parts(6_151_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn resume_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `111`
		//  Estimated: `0`
		// Minimum execution time: 8_151_000 picoseconds.
		Weight::from_parts(8_151_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `n` is `[0, 92]`.
	fn take_first_concatenated_xcm(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_769_000 picoseconds.
		Weight::from_parts(12_786_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_idle_good_msg() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `105683`
		//  Estimated: `0`
		// Minimum execution time: 259_750_000 picoseconds.
		Weight::from_parts(259_750_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_idle_large_msg() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `65752`
		//  Estimated: `0`
		// Minimum execution time: 170_199_000 picoseconds.
		Weight::from_parts(170_199_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
