///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2026 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_robonomics_cps`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-09-29, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `krakov`, CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_cps
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_robonomics_cps.rs
// --header
// /home/akru/devel/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 2
// --repeat
// 1
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_robonomics_cps`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_robonomics_cps::WeightInfo for WeightInfo<T> {
	/// Storage: `CPS::NextNodeId` (r:1 w:1)
	/// Proof: `CPS::NextNodeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Nodes` (r:31 w:1)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:0)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Children` (r:1 w:1)
	/// Proof: `CPS::Children` (`max_values`: None, `max_size`: Some(818), added: 3293, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Payload` (r:0 w:1)
	/// Proof: `CPS::Payload` (`max_values`: None, `max_size`: Some(8210), added: 10685, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Meta` (r:0 w:1)
	/// Proof: `CPS::Meta` (`max_values`: None, `max_size`: Some(1042), added: 3517, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1024]`.
	/// The range of component `p` is `[0, 8192]`.
	fn create_node(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2694`
		//  Estimated: `78769`
		// Minimum execution time: 245_461_000 picoseconds.
		Weight::from_parts(291_095_162, 0)
			.saturating_add(Weight::from_parts(0, 78769))
			// Standard Error: 1_916
			.saturating_add(Weight::from_parts(195, 0).saturating_mul(m.into()))
			// Standard Error: 239
			.saturating_add(Weight::from_parts(3_062, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(34))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `CPS::Nodes` (r:32 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:0)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:32 w:0)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Meta` (r:0 w:1)
	/// Proof: `CPS::Meta` (`max_values`: None, `max_size`: Some(1042), added: 3517, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[0, 1024]`.
	fn set_meta(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `778`
		//  Estimated: `83006`
		// Minimum execution time: 221_337_000 picoseconds.
		Weight::from_parts(250_072_282, 0)
			.saturating_add(Weight::from_parts(0, 83006))
			// Standard Error: 264
			.saturating_add(Weight::from_parts(2_404, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(65))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `CPS::Nodes` (r:32 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:0)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:32 w:0)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Payload` (r:0 w:1)
	/// Proof: `CPS::Payload` (`max_values`: None, `max_size`: Some(8210), added: 10685, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[0, 8192]`.
	fn set_payload(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `815`
		//  Estimated: `83006`
		// Minimum execution time: 221_295_000 picoseconds.
		Weight::from_parts(246_706_043, 0)
			.saturating_add(Weight::from_parts(0, 83006))
			// Standard Error: 18
			.saturating_add(Weight::from_parts(1_954, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(65))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `CPS::Nodes` (r:1 w:1)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:1)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Children` (r:2 w:2)
	/// Proof: `CPS::Children` (`max_values`: None, `max_size`: Some(818), added: 3293, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:32 w:32)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Payload` (r:0 w:1)
	/// Proof: `CPS::Payload` (`max_values`: None, `max_size`: Some(8210), added: 10685, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Meta` (r:0 w:1)
	/// Proof: `CPS::Meta` (`max_values`: None, `max_size`: Some(1042), added: 3517, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 32]`.
	fn delete_node(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1428 + a * (57 ±0)`
		//  Estimated: `7576 + a * (2591 ±0)`
		// Minimum execution time: 93_516_000 picoseconds.
		Weight::from_parts(107_755_770, 0)
			.saturating_add(Weight::from_parts(0, 7576))
			// Standard Error: 15_565
			.saturating_add(Weight::from_parts(1_859_690, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2591).saturating_mul(a.into()))
	}
	/// Storage: `CPS::Nodes` (r:1 w:1)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:2)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:32 w:32)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `CPS::NextScopeId` (r:1 w:1)
	/// Proof: `CPS::NextScopeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 32]`.
	fn create_scope(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `653 + a * (56 ±0)`
		//  Estimated: `3517 + a * (2563 ±0)`
		// Minimum execution time: 70_492_000 picoseconds.
		Weight::from_parts(77_986_808, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			// Standard Error: 6_835
			.saturating_add(Weight::from_parts(2_180_575, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2563).saturating_mul(a.into()))
	}
	/// Storage: `CPS::Nodes` (r:32 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:1)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:1 w:1)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn grant_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1196`
		//  Estimated: `81278`
		// Minimum execution time: 152_163_000 picoseconds.
		Weight::from_parts(171_029_000, 0)
			.saturating_add(Weight::from_parts(0, 81278))
			.saturating_add(T::DbWeight::get().reads(34))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `CPS::Nodes` (r:32 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:1)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:1 w:1)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn revoke_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `745`
		//  Estimated: `81278`
		// Minimum execution time: 151_466_000 picoseconds.
		Weight::from_parts(166_468_000, 0)
			.saturating_add(Weight::from_parts(0, 81278))
			.saturating_add(T::DbWeight::get().reads(34))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
