///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_multisig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `krakov`, CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_multisig
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_multisig.rs
// --header
// /home/akru/devel/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 2
// --repeat
// 1
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_multisig`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_multisig::WeightInfo for WeightInfo<T> {
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_threshold_1(_z: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 50_420_000 picoseconds.
		Weight::from_parts(99_699_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `s` is `[2, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_create(s: u32, z: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `172 + s * (3 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 110_269_000 picoseconds.
		Weight::from_parts(30_950_122, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 822_856
			.saturating_add(Weight::from_parts(793_188, 0).saturating_mul(s.into()))
			// Standard Error: 8_063
			.saturating_add(Weight::from_parts(8_478, 0).saturating_mul(z.into()))
	}
	/// The range of component `s` is `[3, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_approve(s: u32, z: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `282`
		//  Estimated: `0`
		// Minimum execution time: 63_590_000 picoseconds.
		Weight::from_parts(35_017_835, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 130_796
			.saturating_add(Weight::from_parts(285_721, 0).saturating_mul(s.into()))
			// Standard Error: 1_268
			.saturating_add(Weight::from_parts(4_742, 0).saturating_mul(z.into()))
	}
	/// The range of component `s` is `[2, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_complete(s: u32, z: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315 + s * (34 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 93_175_000 picoseconds.
		Weight::from_parts(76_636_224, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 4_559
			.saturating_add(Weight::from_parts(165_387, 0).saturating_mul(s.into()))
			// Standard Error: 44
			.saturating_add(Weight::from_parts(4_942, 0).saturating_mul(z.into()))
	}
	/// The range of component `s` is `[2, 100]`.
	fn approve_as_multi_create(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `172 + s * (3 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 61_260_000 picoseconds.
		Weight::from_parts(91_572_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `s` is `[2, 100]`.
	fn approve_as_multi_approve(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `282`
		//  Estimated: `0`
		// Minimum execution time: 35_395_000 picoseconds.
		Weight::from_parts(55_339_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `s` is `[2, 100]`.
	fn cancel_as_multi(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379 + s * (2 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 55_390_000 picoseconds.
		Weight::from_parts(84_796_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `s` is `[2, 100]`.
	fn poke_deposit(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379 + s * (2 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 58_380_000 picoseconds.
		Weight::from_parts(73_562_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
