///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_collator_selection`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `krakov`, CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_collator_selection
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_collator_selection.rs
// --header
// /home/akru/devel/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 2
// --repeat
// 1
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_collator_selection`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collator_selection::WeightInfo for WeightInfo<T> {
	/// The range of component `b` is `[1, 20]`.
	fn set_invulnerables(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `163 + b * (79 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 28_730_000 picoseconds.
		Weight::from_parts(139_121_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `b` is `[1, 19]`.
	/// The range of component `c` is `[1, 49]`.
	fn add_invulnerable(_b: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `829 + b * (32 ±0) + c * (57 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 83_294_000 picoseconds.
		Weight::from_parts(88_551_524, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 87_847
			.saturating_add(Weight::from_parts(229_781, 0).saturating_mul(c.into()))
	}
	/// The range of component `b` is `[5, 20]`.
	fn remove_invulnerable(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + b * (32 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 23_611_000 picoseconds.
		Weight::from_parts(25_266_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_desired_candidates() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_788_000 picoseconds.
		Weight::from_parts(15_788_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[0, 50]`.
	/// The range of component `k` is `[0, 50]`.
	fn set_candidacy_bond(c: u32, k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + c * (176 ±0) + k * (127 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 25_189_000 picoseconds.
		Weight::from_parts(25_189_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 8_195_004
			.saturating_add(Weight::from_parts(9_621_176, 0).saturating_mul(c.into()))
			// Standard Error: 8_195_004
			.saturating_add(Weight::from_parts(9_462_676, 0).saturating_mul(k.into()))
	}
	/// The range of component `c` is `[4, 50]`.
	fn update_bond(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285 + c * (49 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 46_523_000 picoseconds.
		Weight::from_parts(68_502_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[1, 49]`.
	fn register_as_candidate(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `474 + c * (59 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 67_535_000 picoseconds.
		Weight::from_parts(81_058_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[4, 50]`.
	fn take_candidate_slot(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `607 + c * (59 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 98_571_000 picoseconds.
		Weight::from_parts(108_887_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[4, 50]`.
	fn leave_intent(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302 + c * (49 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 54_446_000 picoseconds.
		Weight::from_parts(72_121_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn note_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `0`
		// Minimum execution time: 68_126_000 picoseconds.
		Weight::from_parts(68_126_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `r` is `[1, 50]`.
	/// The range of component `c` is `[1, 50]`.
	fn new_session(_r: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379 + c * (98 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 37_365_000 picoseconds.
		Weight::from_parts(78_337_030, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 356_926
			.saturating_add(Weight::from_parts(8_124_397, 0).saturating_mul(c.into()))
	}
}
