///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_robonomics_digital_twin`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `krakov`, CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_digital_twin
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_robonomics_digital_twin.rs
// --header
// /home/akru/devel/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 2
// --repeat
// 1
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_robonomics_digital_twin`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_robonomics_digital_twin::WeightInfo for WeightInfo<T> {
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `0`
		// Minimum execution time: 29_274_000 picoseconds.
		Weight::from_parts(29_274_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `0`
		// Minimum execution time: 34_187_000 picoseconds.
		Weight::from_parts(34_187_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn remove_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `0`
		// Minimum execution time: 29_836_000 picoseconds.
		Weight::from_parts(29_836_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
