///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_message_queue`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boot-03`, CPU: `AMD EPYC 4464P 12-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_message_queue
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_message_queue.rs
// --header
// /root/dergudzon/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_message_queue`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_message_queue::WeightInfo for WeightInfo<T> {
	fn ready_ring_knit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `0`
		// Minimum execution time: 8_606_000 picoseconds.
		Weight::from_parts(9_027_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn ready_ring_unknit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `255`
		//  Estimated: `0`
		// Minimum execution time: 7_373_000 picoseconds.
		Weight::from_parts(7_695_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn service_queue_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `0`
		// Minimum execution time: 3_025_000 picoseconds.
		Weight::from_parts(3_156_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn service_page_base_completion() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `0`
		// Minimum execution time: 4_428_000 picoseconds.
		Weight::from_parts(4_548_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn service_page_base_no_completion() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `0`
		// Minimum execution time: 4_449_000 picoseconds.
		Weight::from_parts(4_619_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn service_page_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 106_079_000 picoseconds.
		Weight::from_parts(106_851_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn bump_service_head() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `208`
		//  Estimated: `0`
		// Minimum execution time: 4_719_000 picoseconds.
		Weight::from_parts(4_909_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_service_head() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `198`
		//  Estimated: `0`
		// Minimum execution time: 4_058_000 picoseconds.
		Weight::from_parts(4_278_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn reap_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `105646`
		//  Estimated: `0`
		// Minimum execution time: 44_573_000 picoseconds.
		Weight::from_parts(44_824_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn execute_overweight_page_removed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `105646`
		//  Estimated: `0`
		// Minimum execution time: 60_764_000 picoseconds.
		Weight::from_parts(61_385_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn execute_overweight_page_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `105646`
		//  Estimated: `0`
		// Minimum execution time: 71_264_000 picoseconds.
		Weight::from_parts(71_805_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
