///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2026 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_robonomics_rws`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boot-03`, CPU: `AMD EPYC 4464P 12-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_rws
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_robonomics_rws.rs
// --header
// /root/dergudzon/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_robonomics_rws`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_robonomics_rws::WeightInfo for WeightInfo<T> {
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `0`
		// Minimum execution time: 18_264_000 picoseconds.
		Weight::from_parts(18_725_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_devices() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_937_000 picoseconds.
		Weight::from_parts(4_128_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_393_000 picoseconds.
		Weight::from_parts(1_473_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `0`
		// Minimum execution time: 7_234_000 picoseconds.
		Weight::from_parts(7_494_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn start_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `0`
		// Minimum execution time: 6_161_000 picoseconds.
		Weight::from_parts(6_372_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
