///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2026 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_robonomics_cps`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-09-25, STEPS: `50`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boot-02-robonomics`, CPU: `AMD EPYC 4344P 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_cps
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_robonomics_cps.rs
// --header
// /root/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 50
// --repeat
// 100
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_robonomics_cps`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_robonomics_cps::WeightInfo for WeightInfo<T> {
	/// Storage: `CPS::NextNodeId` (r:1 w:1)
	/// Proof: `CPS::NextNodeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Nodes` (r:32 w:1)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Children` (r:1 w:1)
	/// Proof: `CPS::Children` (`max_values`: None, `max_size`: Some(826), added: 3301, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Payload` (r:0 w:1)
	/// Proof: `CPS::Payload` (`max_values`: None, `max_size`: Some(2074), added: 4549, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Meta` (r:0 w:1)
	/// Proof: `CPS::Meta` (`max_values`: None, `max_size`: Some(2074), added: 4549, mode: `MaxEncodedLen`)
	// NOTE(#671): these three weight functions were regenerated to accept
	// per-byte components (`meta_bytes`/`payload_bytes`/`bytes`) as part of
	// making CPS data operations charge by actual payload size, but the
	// constants below are carried over unchanged from the old
	// worst-case-only benchmarks and do not yet reflect a real per-byte
	// linear model. They must be regenerated via
	// `scripts/runtime-benchmarks.sh` on real benchmark hardware before
	// production use.
	fn create_node(_meta_bytes: u32, _payload_bytes: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3266`
		//  Estimated: `82238`
		// Minimum execution time: 226_154_000 picoseconds.
		Weight::from_parts(234_009_000, 0)
			.saturating_add(Weight::from_parts(0, 82238))
			.saturating_add(T::DbWeight::get().reads(66))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `CPS::Nodes` (r:33 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:0)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:33 w:0)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Meta` (r:0 w:1)
	/// Proof: `CPS::Meta` (`max_values`: None, `max_size`: Some(2074), added: 4549, mode: `MaxEncodedLen`)
	fn set_meta(_bytes: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1010`
		//  Estimated: `85569`
		// Minimum execution time: 213_100_000 picoseconds.
		Weight::from_parts(220_564_000, 0)
			.saturating_add(Weight::from_parts(0, 85569))
			.saturating_add(T::DbWeight::get().reads(98))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `CPS::Nodes` (r:33 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:1 w:0)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:33 w:0)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Payload` (r:0 w:1)
	/// Proof: `CPS::Payload` (`max_values`: None, `max_size`: Some(2074), added: 4549, mode: `MaxEncodedLen`)
	fn set_payload(_bytes: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1047`
		//  Estimated: `85569`
		// Minimum execution time: 213_451_000 picoseconds.
		Weight::from_parts(222_768_000, 0)
			.saturating_add(Weight::from_parts(0, 85569))
			.saturating_add(T::DbWeight::get().reads(98))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// NOTE(#672): `delete_node`'s worst case now also includes deleting a
	// Scope-root leaf filled to `MAX_ACCESS_ENTRIES_PER_SCOPE` `Access`
	// entries (measured separately via the `delete_node_scope_root_worst_case`
	// diagnostic benchmark in `benchmarking.rs`, since it is not a distinct
	// dispatchable). The constant below has not yet been regenerated to
	// account for that worst case and must be reviewed on real benchmark
	// hardware before production use.
	/// Storage: `CPS::Nodes` (r:32 w:1)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Children` (r:2 w:2)
	/// Proof: `CPS::Children` (`max_values`: None, `max_size`: Some(826), added: 3301, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Payload` (r:0 w:1)
	/// Proof: `CPS::Payload` (`max_values`: None, `max_size`: Some(2074), added: 4549, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Meta` (r:0 w:1)
	/// Proof: `CPS::Meta` (`max_values`: None, `max_size`: Some(2074), added: 4549, mode: `MaxEncodedLen`)
	fn delete_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3363`
		//  Estimated: `84777`
		// Minimum execution time: 177_062_000 picoseconds.
		Weight::from_parts(183_334_000, 0)
			.saturating_add(Weight::from_parts(0, 84777))
			.saturating_add(T::DbWeight::get().reads(67))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	// NOTE(#672): `create_scope`'s worst case now also includes the
	// *replacement* path (`node` already roots an active Scope filled to
	// `MAX_ACCESS_ENTRIES_PER_SCOPE` `Access` entries, all synchronously
	// cleared as part of the same call), measured separately via the
	// `create_scope_replace_worst_case` diagnostic benchmark in
	// `benchmarking.rs`, since it is not a distinct dispatchable. The
	// constant below has not yet been regenerated to account for that
	// worst case and must be reviewed on real benchmark hardware before
	// production use.
	/// Storage: `CPS::Nodes` (r:32 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:33 w:1)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:33 w:0)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `CPS::NextScopeId` (r:1 w:1)
	/// Proof: `CPS::NextScopeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn create_scope() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1010`
		//  Estimated: `85569`
		// Minimum execution time: 218_711_000 picoseconds.
		Weight::from_parts(226_135_000, 0)
			.saturating_add(Weight::from_parts(0, 85569))
			.saturating_add(T::DbWeight::get().reads(99))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `CPS::Nodes` (r:32 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:33 w:0)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:1 w:1)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn grant_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `929`
		//  Estimated: `84777`
		// Minimum execution time: 131_156_000 picoseconds.
		Weight::from_parts(135_324_000, 0)
			.saturating_add(Weight::from_parts(0, 84777))
			.saturating_add(T::DbWeight::get().reads(66))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `CPS::Nodes` (r:32 w:0)
	/// Proof: `CPS::Nodes` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Scopes` (r:33 w:0)
	/// Proof: `CPS::Scopes` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CPS::Access` (r:1 w:1)
	/// Proof: `CPS::Access` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn revoke_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1010`
		//  Estimated: `84777`
		// Minimum execution time: 132_449_000 picoseconds.
		Weight::from_parts(137_127_000, 0)
			.saturating_add(Weight::from_parts(0, 84777))
			.saturating_add(T::DbWeight::get().reads(66))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
