///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_xcm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `krakov`, CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_xcm
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_xcm.rs
// --header
// /home/akru/devel/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 2
// --repeat
// 1
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_xcm`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_xcm::WeightInfo for WeightInfo<T> {
	fn send() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `175`
		//  Estimated: `0`
		// Minimum execution time: 71_072_000 picoseconds.
		Weight::from_parts(71_072_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `Benchmark::Override` (r:0 w:0)
	/// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn teleport_assets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
		Weight::from_parts(18_446_744_073_709_551_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `Benchmark::Override` (r:0 w:0)
	/// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn reserve_transfer_assets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
		Weight::from_parts(18_446_744_073_709_551_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn transfer_assets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `340`
		//  Estimated: `0`
		// Minimum execution time: 203_332_000 picoseconds.
		Weight::from_parts(203_332_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `Benchmark::Override` (r:0 w:0)
	/// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn execute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
		Weight::from_parts(18_446_744_073_709_551_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_xcm_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_128_000 picoseconds.
		Weight::from_parts(23_128_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_default_xcm_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_253_000 picoseconds.
		Weight::from_parts(9_253_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_subscribe_version_notify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `175`
		//  Estimated: `0`
		// Minimum execution time: 83_845_000 picoseconds.
		Weight::from_parts(83_845_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_unsubscribe_version_notify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `0`
		// Minimum execution time: 76_150_000 picoseconds.
		Weight::from_parts(76_150_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_suspension() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_921_000 picoseconds.
		Weight::from_parts(8_921_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn migrate_supported_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `23`
		//  Estimated: `0`
		// Minimum execution time: 37_630_000 picoseconds.
		Weight::from_parts(37_630_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn migrate_version_notifiers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `27`
		//  Estimated: `0`
		// Minimum execution time: 36_922_000 picoseconds.
		Weight::from_parts(36_922_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn already_notified_target() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `0`
		// Minimum execution time: 45_896_000 picoseconds.
		Weight::from_parts(45_896_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn notify_current_targets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119`
		//  Estimated: `0`
		// Minimum execution time: 68_042_000 picoseconds.
		Weight::from_parts(68_042_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn notify_target_migration_fail() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `0`
		// Minimum execution time: 29_911_000 picoseconds.
		Weight::from_parts(29_911_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn migrate_version_notify_targets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `34`
		//  Estimated: `0`
		// Minimum execution time: 38_819_000 picoseconds.
		Weight::from_parts(38_819_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn migrate_and_notify_old_targets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119`
		//  Estimated: `0`
		// Minimum execution time: 83_122_000 picoseconds.
		Weight::from_parts(83_122_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn new_query() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_517_000 picoseconds.
		Weight::from_parts(5_517_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn take_response() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7576`
		//  Estimated: `0`
		// Minimum execution time: 48_156_000 picoseconds.
		Weight::from_parts(48_156_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn claim_assets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `0`
		// Minimum execution time: 96_733_000 picoseconds.
		Weight::from_parts(96_733_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `Benchmark::Override` (r:0 w:0)
	/// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_authorized_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
		Weight::from_parts(18_446_744_073_709_551_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `Benchmark::Override` (r:0 w:0)
	/// Proof: `Benchmark::Override` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_authorized_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
		Weight::from_parts(18_446_744_073_709_551_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn weigh_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 35_399_000 picoseconds.
		Weight::from_parts(35_399_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
