///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

//! Autogenerated weights for `pallet_collator_selection`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-17, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `krakov`, CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_collator_selection
// --extrinsic
// *
// --output
// runtime/robonomics/src/weights/pallet_collator_selection.rs
// --header
// /home/akru/devel/robonomics/.github/license-check/HEADER-APACHE2
// --wasm-execution=compiled
// --steps
// 2
// --repeat
// 1
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_collator_selection`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collator_selection::WeightInfo for WeightInfo<T> {
	/// The range of component `b` is `[1, 20]`.
	fn set_invulnerables(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `163 + b * (79 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 26_451_000 picoseconds.
		Weight::from_parts(139_217_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `b` is `[1, 19]`.
	/// The range of component `c` is `[1, 49]`.
	fn add_invulnerable(_b: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `829 + b * (32 ±0) + c * (57 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 80_465_000 picoseconds.
		Weight::from_parts(82_839_583, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 91_690
			.saturating_add(Weight::from_parts(380_416, 0).saturating_mul(c.into()))
	}
	/// The range of component `b` is `[5, 20]`.
	fn remove_invulnerable(_b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + b * (32 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 25_154_000 picoseconds.
		Weight::from_parts(26_986_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_desired_candidates() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_122_000 picoseconds.
		Weight::from_parts(17_122_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[0, 50]`.
	/// The range of component `k` is `[0, 50]`.
	fn set_candidacy_bond(c: u32, k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + c * (176 ±0) + k * (127 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 26_153_000 picoseconds.
		Weight::from_parts(26_153_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 8_707_830
			.saturating_add(Weight::from_parts(10_099_740, 0).saturating_mul(c.into()))
			// Standard Error: 8_707_830
			.saturating_add(Weight::from_parts(10_054_880, 0).saturating_mul(k.into()))
	}
	/// The range of component `c` is `[4, 50]`.
	fn update_bond(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285 + c * (49 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 51_915_000 picoseconds.
		Weight::from_parts(63_611_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[1, 49]`.
	fn register_as_candidate(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `474 + c * (59 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 76_142_000 picoseconds.
		Weight::from_parts(109_708_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[4, 50]`.
	fn take_candidate_slot(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `607 + c * (59 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 105_127_000 picoseconds.
		Weight::from_parts(145_003_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `c` is `[4, 50]`.
	fn leave_intent(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302 + c * (49 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 55_978_000 picoseconds.
		Weight::from_parts(69_766_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn note_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `0`
		// Minimum execution time: 70_268_000 picoseconds.
		Weight::from_parts(70_268_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `r` is `[1, 50]`.
	/// The range of component `c` is `[1, 50]`.
	fn new_session(_r: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `379 + c * (98 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 43_249_000 picoseconds.
		Weight::from_parts(88_610_683, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 125_644
			.saturating_add(Weight::from_parts(8_656_173, 0).saturating_mul(c.into()))
	}
}
