(function() {var implementors = {};
implementors["alpha_runtime"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"alpha_runtime/struct.GenesisConfig.html\" title=\"struct alpha_runtime::GenesisConfig\">GenesisConfig</a>","synthetic":false,"types":["alpha_runtime::GenesisConfig"]}];
implementors["ipci_runtime"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ipci_runtime/struct.GenesisConfig.html\" title=\"struct ipci_runtime::GenesisConfig\">GenesisConfig</a>","synthetic":false,"types":["ipci_runtime::GenesisConfig"]}];
implementors["local_runtime"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"local_runtime/struct.GenesisConfig.html\" title=\"struct local_runtime::GenesisConfig\">GenesisConfig</a>","synthetic":false,"types":["local_runtime::GenesisConfig"]}];
implementors["main_runtime"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"main_runtime/struct.GenesisConfig.html\" title=\"struct main_runtime::GenesisConfig\">GenesisConfig</a>","synthetic":false,"types":["main_runtime::GenesisConfig"]}];
implementors["pallet_robonomics_datalog"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_robonomics_datalog/pallet/trait.Config.html\" title=\"trait pallet_robonomics_datalog::pallet::Config\">Config</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"pallet_robonomics_datalog/pallet/struct.RingBufferItem.html\" title=\"struct pallet_robonomics_datalog::pallet::RingBufferItem\">RingBufferItem</a>&lt;T&gt;","synthetic":false,"types":["pallet_robonomics_datalog::pallet::RingBufferItem"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"pallet_robonomics_datalog/pallet/struct.RingBufferIndex.html\" title=\"struct pallet_robonomics_datalog::pallet::RingBufferIndex\">RingBufferIndex</a>","synthetic":false,"types":["pallet_robonomics_datalog::pallet::RingBufferIndex"]}];
implementors["pallet_robonomics_rws"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"pallet_robonomics_rws/enum.Subscription.html\" title=\"enum pallet_robonomics_rws::Subscription\">Subscription</a>","synthetic":false,"types":["pallet_robonomics_rws::Subscription"]}];
implementors["pallet_robonomics_staking"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_robonomics_staking/pallet/trait.Config.html\" title=\"trait pallet_robonomics_staking::pallet::Config\">Config</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"pallet_robonomics_staking/pallet/struct.GenesisConfig.html\" title=\"struct pallet_robonomics_staking::pallet::GenesisConfig\">GenesisConfig</a>&lt;T&gt;","synthetic":false,"types":["pallet_robonomics_staking::pallet::GenesisConfig"]}];
implementors["robonomics_service"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"robonomics_service/chain_spec/struct.Extensions.html\" title=\"struct robonomics_service::chain_spec::Extensions\">Extensions</a>","synthetic":false,"types":["robonomics_service::chain_spec::Extensions"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"robonomics_service/parachain/chain_spec/struct.Extensions.html\" title=\"struct robonomics_service::parachain::chain_spec::Extensions\">Extensions</a>","synthetic":false,"types":["robonomics_service::parachain::chain_spec::Extensions"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()