///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////
//! Autogenerated weights for `pallet_wrapped_asset`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: YYYY-MM-DD, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark-host`, CPU: `<CPUNAME>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("robonomics-dev")`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=target/release/wbuild/robonomics-runtime/robonomics_runtime.wasm
// --pallet=pallet_wrapped_asset
// --extrinsic=*
// --steps=50
// --repeat=20
// --heap-pages=4096
// --output=./frame/wrapped-asset/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_wrapped_asset`.
pub trait WeightInfo {
    fn wrap_and_send() -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    /// Storage: `WrappedNative::TotalWrapped` (r:1 w:1)
    /// Proof: `WrappedNative::TotalWrapped` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Account` (r:1 w:1)
    /// Proof: `Balances::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `PolkadotXcm::XcmExecutionSuspended` (r:1 w:0)
    /// Proof: `PolkadotXcm::XcmExecutionSuspended` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn wrap_and_send() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `171`
        //  Estimated: `3636`
        // Minimum execution time: 50_000 picoseconds.
        Weight::from_parts(55_000_000, 3636)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}

#[cfg(test)]
mod tests {
    use frame_support::weights::Weight;
    use super::*;

    #[test]
    fn test_wrap_and_send() {
        assert!(<() as WeightInfo>::wrap_and_send().ref_time() > 0);
    }
}

// Import required for unit weight implementation
use frame_support::weights::constants::RocksDbWeight;
