///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////
//! Autogenerated weights for `pallet_xcm_info`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: YYYY-MM-DD, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark-host`, CPU: `<CPUNAME>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("robonomics-dev")`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=target/release/wbuild/robonomics-runtime/robonomics_runtime.wasm
// --pallet=pallet_xcm_info
// --extrinsic=*
// --steps=50
// --repeat=20
// --heap-pages=4096
// --output=./frame/xcm-info/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_xcm_info`.
pub trait WeightInfo {
    fn set_relay_network() -> Weight;
    fn set_asset_link() -> Weight;
}

/// Weights for `pallet_xcm_info` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `XcmInfo::RelayNetwork` (r:0 w:1)
    /// Proof: `XcmInfo::RelayNetwork` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn set_relay_network() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_000 picoseconds.
        Weight::from_parts(6_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `XcmInfo::LocationToAssetId` (r:0 w:1)
    /// Proof: `XcmInfo::LocationToAssetId` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `XcmInfo::AssetIdToLocation` (r:0 w:1)
    /// Proof: `XcmInfo::AssetIdToLocation` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn set_asset_link() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_000 picoseconds.
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    /// Storage: `XcmInfo::RelayNetwork` (r:0 w:1)
    /// Proof: `XcmInfo::RelayNetwork` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn set_relay_network() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_000 picoseconds.
        Weight::from_parts(6_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    /// Storage: `XcmInfo::LocationToAssetId` (r:0 w:1)
    /// Proof: `XcmInfo::LocationToAssetId` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `XcmInfo::AssetIdToLocation` (r:0 w:1)
    /// Proof: `XcmInfo::AssetIdToLocation` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn set_asset_link() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_000 picoseconds.
        Weight::from_parts(10_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}

#[cfg(test)]
mod tests {
    use frame_support::weights::Weight;
    use super::*;

    #[test]
    fn test_set_relay_network() {
        assert!(SubstrateWeight::<()>::set_relay_network().ref_time() > 0);
        assert!(<() as WeightInfo>::set_relay_network().ref_time() > 0);
    }

    #[test]
    fn test_set_asset_link() {
        assert!(SubstrateWeight::<()>::set_asset_link().ref_time() > 0);
        assert!(<() as WeightInfo>::set_asset_link().ref_time() > 0);
    }
}

// Import required for unit weight implementation
use frame_support::weights::constants::RocksDbWeight;
