///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////
//! Autogenerated weights for `pallet_robonomics_cps`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-02, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `13th Gen Intel(R) Core(TM) i7-1365U`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_cps
// --extrinsic
// *
// --template
// ./scripts/weights/frame-weight-template.hbs
// --output
// frame/cps/src/weights.rs
// --header
// ./LICENSE
// --steps
// 2
// --repeat
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_robonomics_cps`.
pub trait WeightInfo {
	fn create_node() -> Weight;
	fn set_meta() -> Weight;
	fn set_payload() -> Weight;
	fn move_node() -> Weight;
	fn delete_node() -> Weight;
}

/// Weights for `pallet_robonomics_cps` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `0`
		// Minimum execution time: 30_942_000 picoseconds.
		Weight::from_parts(30_942_000, 0)
	}
	fn set_meta() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `0`
		// Minimum execution time: 21_430_000 picoseconds.
		Weight::from_parts(21_430_000, 0)
	}
	fn set_payload() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `0`
		// Minimum execution time: 26_888_000 picoseconds.
		Weight::from_parts(26_888_000, 0)
	}
	fn move_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `0`
		// Minimum execution time: 49_712_000 picoseconds.
		Weight::from_parts(49_712_000, 0)
	}
	fn delete_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `198`
		//  Estimated: `0`
		// Minimum execution time: 39_238_000 picoseconds.
		Weight::from_parts(39_238_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `0`
		// Minimum execution time: 30_942_000 picoseconds.
		Weight::from_parts(30_942_000, 0)
	}
	fn set_meta() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `0`
		// Minimum execution time: 21_430_000 picoseconds.
		Weight::from_parts(21_430_000, 0)
	}
	fn set_payload() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `0`
		// Minimum execution time: 26_888_000 picoseconds.
		Weight::from_parts(26_888_000, 0)
	}
	fn move_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `0`
		// Minimum execution time: 49_712_000 picoseconds.
		Weight::from_parts(49_712_000, 0)
	}
	fn delete_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `198`
		//  Estimated: `0`
		// Minimum execution time: 39_238_000 picoseconds.
		Weight::from_parts(39_238_000, 0)
	}
}
