[package]
name = "clisrv"
version = "0.1.0"
authors = ["am <yamukha@ukr.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std ="1.9.0"
bincode = "1.3.3"
chrono = "0.4"
libp2p = " 0.38.0"
libp2p-yamux = "0.32.0"
libp2prs-runtime = {  version = "0.3.0" }
rust-base58  = "0.0.4"
robonomics-protocol = { path = "../.." }
structopt = { version = "0.3", default-features = false }
log = "0.4.6"
env_logger = "0.6.0"