
//! Autogenerated weights for `pallet_robonomics_rws`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-10-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `11th Gen Intel(R) Core(TM) i5-1130G7 @ 1.10GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_rws
// --extrinsic
// 
// --template
// ./scripts/weights/frame-weight-template.hbs
// --output
// frame/rws/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_robonomics_rws`.
pub trait WeightInfo {
	fn bid() -> Weight;
	fn set_devices() -> Weight;
	fn set_oracle() -> Weight;
	fn set_subscription() -> Weight;
	fn start_auction() -> Weight;
}

/// Weights for `pallet_robonomics_rws` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RWS::AuctionQueue` (r:1 w:0)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:1 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `17871`
		// Minimum execution time: 55_738_000 picoseconds.
		Weight::from_parts(56_962_000, 17871)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `RWS::Devices` (r:0 w:1)
	/// Proof: `RWS::Devices` (`max_values`: None, `max_size`: Some(1065), added: 3540, mode: `MaxEncodedLen`)
	fn set_devices() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_100_000 picoseconds.
		Weight::from_parts(14_715_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::Oracle` (r:0 w:1)
	/// Proof: `RWS::Oracle` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_452_000 picoseconds.
		Weight::from_parts(5_795_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::Oracle` (r:1 w:0)
	/// Proof: `RWS::Oracle` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Ledger` (r:0 w:1)
	/// Proof: `RWS::Ledger` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn set_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `1517`
		// Minimum execution time: 24_933_000 picoseconds.
		Weight::from_parts(25_435_000, 1517)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::AuctionNext` (r:1 w:1)
	/// Proof: `RWS::AuctionNext` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RWS::AuctionQueue` (r:1 w:1)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:0 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn start_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `17871`
		// Minimum execution time: 20_883_000 picoseconds.
		Weight::from_parts(21_266_000, 17871)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RWS::AuctionQueue` (r:1 w:0)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:1 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `17871`
		// Minimum execution time: 55_738_000 picoseconds.
		Weight::from_parts(56_962_000, 17871)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `RWS::Devices` (r:0 w:1)
	/// Proof: `RWS::Devices` (`max_values`: None, `max_size`: Some(1065), added: 3540, mode: `MaxEncodedLen`)
	fn set_devices() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_100_000 picoseconds.
		Weight::from_parts(14_715_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::Oracle` (r:0 w:1)
	/// Proof: `RWS::Oracle` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_452_000 picoseconds.
		Weight::from_parts(5_795_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::Oracle` (r:1 w:0)
	/// Proof: `RWS::Oracle` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Ledger` (r:0 w:1)
	/// Proof: `RWS::Ledger` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn set_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `1517`
		// Minimum execution time: 24_933_000 picoseconds.
		Weight::from_parts(25_435_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::AuctionNext` (r:1 w:1)
	/// Proof: `RWS::AuctionNext` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RWS::AuctionQueue` (r:1 w:1)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:0 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn start_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `17871`
		// Minimum execution time: 20_883_000 picoseconds.
		Weight::from_parts(21_266_000, 17871)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
