///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2025 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////
//! Autogenerated weights for `pallet_robonomics_rws`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-10-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `DO-Premium-AMD`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/robonomics-runtime/robonomics_runtime.compact.compressed.wasm
// --pallet
// pallet_robonomics_rws
// --extrinsic
// 
// --template
// ./scripts/weights/frame-weight-template.hbs
// --output
// frame/rws/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_robonomics_rws`.
pub trait WeightInfo {
	fn bid() -> Weight;
	fn claim() -> Weight;
	fn start_auction() -> Weight;
}

/// Weights for `pallet_robonomics_rws` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RWS::AuctionQueue` (r:1 w:0)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:1 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `17871`
		// Minimum execution time: 47_900_000 picoseconds.
		Weight::from_parts(52_469_000, 17871)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
    // TODO: run benchmark
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_720_000 picoseconds.
		Weight::from_parts(13_480_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::AuctionNext` (r:1 w:1)
	/// Proof: `RWS::AuctionNext` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RWS::AuctionQueue` (r:1 w:1)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:0 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn start_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `17871`
		// Minimum execution time: 18_170_000 picoseconds.
		Weight::from_parts(24_099_000, 17871)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RWS::AuctionQueue` (r:1 w:0)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:1 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `17871`
		// Minimum execution time: 47_900_000 picoseconds.
		Weight::from_parts(52_469_000, 17871)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
    // TODO: run benchmark
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_720_000 picoseconds.
		Weight::from_parts(13_480_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RWS::AuctionNext` (r:1 w:1)
	/// Proof: `RWS::AuctionNext` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RWS::AuctionQueue` (r:1 w:1)
	/// Proof: `RWS::AuctionQueue` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `RWS::Auction` (r:0 w:1)
	/// Proof: `RWS::Auction` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn start_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `17871`
		// Minimum execution time: 18_170_000 picoseconds.
		Weight::from_parts(24_099_000, 17871)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
