[package]
name = "node-bench"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node integration benchmarks."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
node-primitives = { path = "../primitives" } 
node-testing = { path = "../testing" } 
node-runtime = { path = "../runtime" }
sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-state-machine = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
serde = "1.0.101"
serde_json = "1.0.41"
structopt = "0.3"
derive_more = "0.99.2"
kvdb = "0.9.0"
kvdb-rocksdb = "0.11.0"
sp-trie = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-timestamp = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-tracing = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
hash-db = "0.15.2"
tempfile = "3.1.0"
fs_extra = "1"
hex = "0.4.0"
rand = { version = "0.7.2", features = ["small_rng"] }
lazy_static = "1.4.0"
parity-util-mem = { version = "0.9.0", default-features = false, features = ["primitive-types"] }
parity-db = { version = "0.2.2" }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
futures = { version = "0.3.4", features = ["thread-pool"] }
