[package]
name = "robonomics-sensors"
description = "Robonomics Network supported sensors."
version = "0.2.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
serde = "1.0.106"
futures = "0.3.4"
derive_more = "0.99"
serialport = "3.3"
sds011 = "0.1"
log = "0.4"
