name: Cachix builder

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
    outputs:
      status:
        description: "Status of the cachix builds"
        value: ${{ jobs.developer-shell-check.outputs.status && jobs.package-build.outputs.status }}

permissions:
  contents: read

concurrency:
  group: cachix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  developer-shell-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup runner
        uses: ./.github/actions/setup-runner
        with:
          cachix_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix develop --command bash -c "echo OK"
      - run: nix develop .#benchmarking --command bash -c "echo OK"

  package-build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    strategy:
      matrix:
        include:
          - arch: x86_64
          - arch: aarch64
    steps:
      - uses: actions/checkout@v4

      - name: Setup runner
        uses: ./.github/actions/setup-runner
        with:
          cachix_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: |
          CORES=$(nproc)
          CORES=$((CORES - 1))
          echo "Using $CORES cores."
          nix build -L --cores "$CORES" -o ${{ matrix.arch }} .#package-${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: package-linux-${{ matrix.arch }}
          path: ${{ matrix.arch }}/package.tar.gz
          retention-days: 7
