name: Cachix builder

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
    outputs:
      status:
        description: "Status of the cachix builds"
        value: ${{ jobs.cachix-upload.outputs.status }}

permissions:
  contents: read

concurrency:
  group: cachix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cachix-builds:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup runner
        uses: ./.github/actions/setup-runner
        with:
          cachix_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix develop --command bash -c "echo OK"
      - run: nix develop .#benchmarking --command bash -c "echo OK"

      - name: Build x86_64 distribution 
        run: |
          CORES=$(nproc)
          CORES=$((CORES - 1))
          echo "Using $CORES cores."
          nix build -L --cores "$CORES" .#dist-x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: robonomics-linux-x86_64
          path: result/dist.tar.gz
          retention-days: 7

      - name: Build aarch64 distribution 
        run: |
          CORES=$(nproc)
          CORES=$((CORES - 1))
          echo "Using $CORES cores."
          nix build -L --cores "$CORES" .#dist-aarch64

      - uses: actions/upload-artifact@v4
        with:
          name: robonomics-linux-aarch64
          path: result/dist.tar.gz 
          retention-days: 7
