name: Cachix builder

on:
  push:
    branches:
    - 'master'
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
    outputs:
      status:
        description: "Status of the cachix builds"
        value: ${{ jobs.developer-shell-check.outputs.status == 'success' }}

permissions:
  contents: read

concurrency:
  group: cachix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  developer-shell-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup runner
        uses: ./.github/actions/setup-runner
        with:
          cachix_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix develop --command bash -c "echo OK"
      - run: nix develop .#benchmarking --command bash -c "echo OK"
