name: Nightly
permissions:
  contents: read

on:
  push:
    branches:
    - 'master'
    - 'release/*'

  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
    outputs:
      status:
        description: "Status of nightly builds"
        value: ${{ jobs.docker.outputs.status == 'success' && jobs.srtool.outputs.status == 'success' }}

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

env:
  SUBWASM_VERSION: 0.16.1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
#  tests:
#    uses: ./.github/workflows/tests.yml

#  check-metadata:
#    uses: ./.github/workflows/metadata-check.yml

#  cachix:
#    needs: [tests, check-metadata]
#    uses: ./.github/workflows/cachix.yml
#    secrets:
#      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

#  robonet:
#    needs: tests
#    uses: ./.github/workflows/robonet.yml
#    secrets:
#      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-binaries:
#    needs: tests
    name: Binary - ${{ matrix.platform.os-name }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: linux-x86_64
            runs-on: ubuntu-26.04
            target: x86_64-unknown-linux-musl
          - os-name: linux-aarch64
            runs-on: ubuntu-26.04-arm
            target: aarch64-unknown-linux-musl 
          - os-name: macos-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
          - os-name: macos-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.platform.target }}

      - name: Install linux deps
        if: ${{ startsWith(matrix.platform.os-name, 'linux') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential musl-tools protobuf-compiler pkg-config lld-21 \
            clang-21 clang-tools-21 libclang-common-21-dev libclang-21-dev libclang1-21 \
            libjemalloc-dev librocksdb-dev

      - name: Install macos deps
        if: ${{ startsWith(matrix.platform.os-name, 'macos') }}
        run: |
          brew install llvm@21 rocksdb

      - name: Build binaries
        env:
          CC: clang
          CXX: clang++
          RUSTFLAGS: -Clinker-plugin-lto -Clinker=clang -Clink-arg=-fuse-ld=lld
          LIBCLANG_PATH: ${{ case(startsWith(matrix.platform.os-name, 'linux'), '/usr/lib/llvm-21/lib', '/opt/homebrew/opt/llvm@21/lib') }}
        run: cargo build --profile=production --target=${{ matrix.platform.target }}

      - name: Create tarball
        run: |
          cd target/${{ matrix.platform.target }}/production && tar czvf package.tar.gz robonomics cps

      - uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.platform.os-name }}
          path: target/${{ matrix.platform.target }}/production/package.tar.gz
          retention-days: 7

  docker:
    needs: build-binaries 
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}

    steps:
    - name: Checkout the source code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: robonomics/robonomics
        tags: type=sha # add git short SHA as Docker tag

    - name: Download pre-built amd64 binaries
      uses: actions/download-artifact@v4
      with:
        name: package-linux-x86_64
        path: scripts/docker/amd64/
    - run: cd scripts/docker/amd64 && tar xvf package.tar.gz

    - name: Download pre-built aarch64 binaries 
      uses: actions/download-artifact@v4
      with:
        name: package-linux-aarch64
        path: scripts/docker/arm64/
    - run: cd scripts/docker/arm64 && tar xvf package.tar.gz

    - name: Build & Push docker image
      uses: docker/build-push-action@v6
      with:
        context: scripts/docker
        platforms: linux/amd64,linux/arm64
        labels: ${{ steps.docker_meta.outputs.labels }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

  srtool:
#    needs: tests 
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}

    steps:
    - uses: actions/checkout@v5

    - name: Srtool build
      id: srtool_build
      uses: chevdor/srtool-actions@v0.9.2
      env:
        BUILD_OPTS: "--features on-chain-release-build"
      with:
        chain: robonomics 
        runtime_dir: runtime/robonomics

    - name: Summary
      run: |
        echo '${{ steps.srtool_build.outputs.json }}' | jq > robonomics-srtool-digest.json
        cat robonomics-srtool-digest.json
        echo "Compact Runtime: ${{ steps.srtool_build.outputs.wasm }}"
        echo "Compressed Runtime: ${{ steps.srtool_build.outputs.wasm_compressed }}"
        cp ${{ steps.srtool_build.outputs.wasm }} robonomics_runtime.compact.wasm
        cp ${{ steps.srtool_build.outputs.wasm_compressed }} robonomics_runtime.compact.compressed.wasm

    # We now get extra information thanks to subwasm
    - name: Install subwasm
      run: |
        wget https://github.com/chevdor/subwasm/releases/download/v${{ env.SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
        sudo dpkg -i subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
        subwasm --version

    - name: Show Runtime information
      shell: bash
      run: |
        subwasm info ${{ steps.srtool_build.outputs.wasm }}
        subwasm info ${{ steps.srtool_build.outputs.wasm_compressed }}
        subwasm --json info ${{ steps.srtool_build.outputs.wasm }} > robonomics-info.json
        subwasm --json info ${{ steps.srtool_build.outputs.wasm_compressed }} > robonomics-compressed-info.json

    - name: Extract the metadata
      shell: bash
      run: |
        subwasm meta ${{ steps.srtool_build.outputs.wasm }}
        subwasm --json meta ${{ steps.srtool_build.outputs.wasm }} > robonomics-metadata.json

    - name: Check the metadata diff
      shell: bash
      # the following subwasm call will error for chains that are not known and/or live, that includes shell for instance
      run: |
        subwasm diff ${{ steps.srtool_build.outputs.wasm }} --chain-b robonomics || \
          echo "Subwasm call failed, check the logs. This is likely because robonomics is not known by subwasm" | \
          tee robonomics-diff.txt

    - name: Archive Artifacts for robonomics runtime
      uses: actions/upload-artifact@v4
      with:
        name: robonomics-runtime
        path: |
          robonomics_runtime.compact.wasm
          robonomics_runtime.compact.compressed.wasm
          robonomics-srtool-digest.json
          robonomics-info.json
          robonomics-compressed-info.json
          robonomics-metadata.json
          robonomics-diff.txt
