name: Static Analysis
on: [push, workflow_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  fmt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt -y install protobuf-compiler

      - name: Install & display rust toolchain
        run: rustup show

      - name: Check targets are installed correctly
        run: rustup target list --installed

      - name: Check fmt
        run: cargo fmt -- --check

      - name: Check Cargo.toml format
        run: |
          if taplo --version &> /dev/null; then
            echo "taplo-cli is already installed"
          else
            cargo install taplo-cli
          fi
          taplo fmt --check

  clippy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt -y install protobuf-compiler

    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean

    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: WASM
      run: rustup component add rust-src --toolchain 1.81.0-x86_64-unknown-linux-gnu

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --features runtime-benchmarks
        # TODO: Temporary permit warnings, remove it later when fix
        #-- -D warnings

  check-license:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Check license
        uses: viperproject/check-license-header@v2
        with:
          path: ./
          config: ./.github/license-check/config.json
          strict: false
